---
title: "about"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Final Project Version 1

# Background

The goal of this project is to analyze obesity trends in the United States, and how these specifically relate to food availability statistics in the country. 
The American Center for Disease Control and Prevention states that obesity can be caused by a number of factors, including but not limited to "dietary patterns, physical activity, inactivity, medication use, and other exposures". According to the CDC, obesity is associated with "poorer mental health outcomes, reduced quality of life, and the leading causes of death in the U.S". These causes include life-threatening diseases such as cancer, diabetes, and heart disease. 
If we look at statistics we will see that a large percentage of the U.S population is considered to be obese. That is why, it is not uncommon to hear the phrase that rising obesity in the U.S is a Public Health Crisis; and one that requires a thorough assessment and solution.
The aim of this project is to look at the prevalence of different factors that may affect obesity rates; namely accessibility to healthy foods, and how they might correlate with the issue facing the country. Finding and counteracting potential sources that may contribute to obesity may be a first step in the right direction.

# Datasets

The first dataset that I have compiled is from the CDC's website containing statistics about the rate of obesity in the US across the years. It looks at the percentage of the population by state that is obese or overweight, as well as those who exercise and those who eat fruits and vegetables. It also breaks down the population based on certain characteristics such as gender, income, race, and education. So far in terms of cleaning, I have removed columns that I don't suspect I will need for the project, and I have renamed column titles. However, if you look at the dataset you will find that a lot of the observation values are blank. That is because each row looks at a specific observation (i.e. obesity or activity) for a specific population (i.e female or asian population). In addition this is repeated for each year. I have not grouped the data or filtered it in any way, because I have not decided what variables I will want to focus on for my project. So I will do that further down the line. 
The link to access this dataset is the following: https://chronicdata.cdc.gov/Nutrition-Physical-Activity-and-Obesity/Nutrition-Physical-Activity-and-Obesity-Behavioral/hn4x-zwk7

The second dataset I have compiled if from the United States' Department of Agriculture Economic Research Service website, containing statistics about food secuirty and access to healthy nutrition throughout the US. The excel file I download actually contains several sheets with different data statistics, namely access to food, stores, restaurants, and information across all counties and states in the US. In terms of cleaning, so far I have only assigned specific variables to specific sheets and rounded numbers. Because I have not decided what data I will surely use for my project, I cannot remove specific observations or variables and will do that later on.I also suspect that I might use more datasets present on the same website.
The link to the dataset is the following:
https://www.ers.usda.gov/data-products/food-access-research-atlas/download-the-data/

Finally, the link to my github repo for this milestone is: https://github.com/Alexou07/final_project_v1 and my data is marked and collected in the gather.rmd.

## Gathered Data by State

Gathered in my repo is data collected from both the CDC and United States Department of Agriculture Economic Research Service website. This week I have started working no the data from the CDC website which looks at statistics regarding obesity in the US. I have started to compile by states variables which store the progression in percentage of population who is obese or overweight, by gender, race and income. I made functions that would allow me to do that for each variable, and then assigned them to states. For the future of my app I hope to be able to produce maps and informational graphics demonstrating in what ways these statistics might be correlated with food access and physical activity statistics.

The link to my repo is the following: https://github.com/Alexou07/final_project_v1
