---
title: "State Data"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(janitor)
library(readxl)
library(dplyr)
```

## Obesity rates by State in the female population

```{r, National, echo=FALSE}

national_stats <- read.csv("raw-data/Nutrition_Physical_Activity_and_Obesity.csv") %>%
  pivot_wider(names_from = "Question", values_from = "Data_Value") %>%
  subset(select = -c(Datasource, Topic, Class, Data_Value_Unit, Data_Value_Type, Data_Value_Alt, Data_Value_Footnote, Data_Value_Footnote_Symbol, Low_Confidence_Limit, High_Confidence_Limit, Total, Education, GeoLocation, ClassID, TopicID, QuestionID, DataValueTypeID, LocationID, StratificationCategory1, Stratification1, StratificationCategoryId1, StratificationID1))%>%
  clean_names() %>%
  rename(overweight = percent_of_adults_aged_18_years_and_older_who_have_an_overweight_classification, 
         no_phys_activity = percent_of_adults_who_engage_in_no_leisure_time_physical_activity, 
         hi_phys_active = percent_of_adults_who_achieve_at_least_150_minutes_a_week_of_moderate_intensity_aerobic_physical_activity_or_75_minutes_a_week_of_vigorous_intensity_aerobic_physical_activity_and_engage_in_muscle_strengthening_activities_on_2_or_more_days_a_week, 
         med_phys_active = percent_of_adults_who_achieve_at_least_300_minutes_a_week_of_moderate_intensity_aerobic_physical_activity_or_150_minutes_a_week_of_vigorous_intensity_aerobic_activity_or_an_equivalent_combination,
         mod_phys_active = percent_of_adults_who_achieve_at_least_150_minutes_a_week_of_moderate_intensity_aerobic_physical_activity_or_75_minutes_a_week_of_vigorous_intensity_aerobic_activity_or_an_equivalent_combination,
         obesity = percent_of_adults_aged_18_years_and_older_who_have_obesity, 
         fruit = percent_of_adults_who_report_consuming_fruit_less_than_one_time_daily, 
         vegetables = percent_of_adults_who_report_consuming_vegetables_less_than_one_time_daily) %>%
  subset(select = -percent_of_adults_who_engage_in_muscle_strengthening_activities_on_2_or_more_days_a_week) %>%
  arrange(location_abbr)

```

```{r functions, echo=FALSE}
get_female_obesity <- function(x){
  national_stats %>%
  filter(location_desc == x & gender == "Female" & !is.na(obesity)) %>%
  select(year_end, location_desc, sample_size, gender, obesity) %>%
  arrange(year_end)
}

get_female_overweight <- function(x){
  national_stats %>%
  filter(location_desc == x, gender == "Female" & !is.na(overweight)) %>%
  select(year_end, location_desc, sample_size, gender, overweight) %>%
  arrange(year_end)
}

get_male_overweight <- function(x){
  national_stats %>%
  filter(location_desc == x, gender == "Male" & !is.na(overweight)) %>%
  select(year_end, location_desc, sample_size, gender, overweight) %>%
  arrange(year_end)
}

get_male_obesity <- function(x){
  national_stats %>%
  filter(location_desc == x & gender == "Male" & !is.na(obesity)) %>%
  select(year_end, location_desc, sample_size, gender, obesity) %>%
  arrange(year_end)
}

get_race_obesity <- function(x){
  national_stats %>%
  filter(location_desc == x & !is.na(sample_size) & !is.na(race_ethnicity) & race_ethnicity != "" & !is.na(obesity)) %>%
  select(year_end, location_desc, sample_size, race_ethnicity, obesity) %>%
  arrange(year_end)
}

get_income_obesity <- function(x){
  national_stats %>%
  filter(location_desc == x & !is.na(sample_size) & !is.na(income) & income != "" & income != "Data not reported" & !is.na(obesity)) %>%
  select(year_end, location_desc, sample_size, income, obesity) %>%
  arrange(year_end)
}
```

```{r Alaska, echo=FALSE}
AK_female_obesity <- get_female_obesity("Alaska")

AK_male_obesity <- get_male_obesity("Alaska")

AK_female_overweight <- get_female_overweight("Alaska")

AK_male_overweight <- get_male_overweight("Alaska")

AK_race_obese <- get_race_obesity("Alaska")

AK_income_obese <- get_income_obesity("Alaska")
  
```

```{r Alabama, echo=FALSE}
AL_female_obesity <- get_female_obesity("Alabama")

AL_male_obesity <- get_male_obesity("Alabama")

AL_female_overweight <- get_female_overweight("Alabama")

AL_male_overweight <- get_male_overweight("Alabama")

AL_race_obese <- get_race_obesity("Alabama")

AL_income_obese <- get_income_obesity("Alabama")
```

```{r Arizona, echo=FALSE}
AZ_female_obesity <- get_female_obesity("Arizona")

AZ_male_obesity <- get_male_obesity("Arizona")

AZ_female_overweight <- get_female_overweight("Arizona")

AZ_male_overweight <- get_male_overweight("Arizona")

AZ_race_obese <- get_race_obesity("Arizona")

AZ_income_obese <- get_income_obesity("Arizona")
```

```{r Arkansas, echo=FALSE}
AR_female_obesity <- get_female_obesity("Arkansas")

AR_male_obesity <- get_male_obesity("Arkansas")

AR_female_overweight <- get_female_overweight("Arkansas")

AR_male_overweight <- get_male_overweight("Arkansas")

AR_race_obese <- get_race_obesity("Arkansas")

AR_income_obese <- get_income_obesity("Arkansas")
```

```{r California, echo=FALSE}
CA_female_obesity <- get_female_obesity("California")

CA_male_obesity <- get_male_obesity("California")

CA_female_overweight <- get_female_overweight("California")

CA_male_overweight <- get_male_overweight("California")

CA_race_obese <- get_race_obesity("California")

CA_income_obese <- get_income_obesity("California")
```

```{r Colorda, echo=FALSE}
CO_female_obesity <- get_female_obesity("Colorado")

CO_male_obesity <- get_male_obesity("Colorado")

CO_female_overweight <- get_female_overweight("Colorado")

CO_male_overweight <- get_male_overweight("Colorado")

CO_race_obese <- get_race_obesity("Colorado")

CO_income_obese <- get_income_obesity("Colorado")
```

```{r Connecticut, echo=FALSE}
CT_female_obesity <- get_female_obesity("Connecticut")

CT_male_obesity <- get_male_obesity("Connecticut")

CT_female_overweight <- get_female_overweight("Connecticut")

CT_male_overweight <- get_male_overweight("Connecticut")

CT_race_obese <- get_race_obesity("Connecticut")

CT_income_obese <- get_income_obesity("Connecticut")
```

```{r Delaware, echo=FALSE}
DE_female_obesity <- get_female_obesity("Delaware")

DE_male_obesity <- get_male_obesity("Delaware")

DE_female_overweight <- get_female_overweight("Delaware")

DE_male_overweight <- get_male_overweight("Delaware")

DE_race_obesity <- get_race_obesity("Delaware")

DE_income_obesity <- get_income_obesity("Delaware")
```

```{r Florida, echo=FALSE}
FL_female_obesity <- get_female_obesity("Florida")

FL_male_obesity <- get_male_obesity("Florida")

FL_female_overweight <- get_female_overweight("Florida")

FL_male_overweight <- get_male_overweight("Florida")

FL_race_obesity <- get_race_obesity("Florida")

FL_income_obesity <- get_income_obesity("Florida")
```

```{r Georgia, echo=FALSE}
GA_female_obesity <- get_female_obesity("Georgia")

GA_male_obesity <- get_male_obesity("Georgia")

GA_female_overweight <- get_female_overweight("Georgia")

GA_male_overweight <- get_male_overweight("Georgia")

GA_race_obesity <- get_race_obesity("Georgia")

GA_income_obesity <- get_income_obesity("Georgia")

```

```{r Hawaii, echo=FALSE}
HI_female_obesity <- get_female_obesity("Hawaii")

HI_male_obesity <- get_male_obesity("Hawaii")

HI_female_overweight <- get_female_overweight("Hawaii")

HI_male_overweight <- get_male_overweight("Hawaii")

HI_race_obesity <- get_race_obesity("Hawaii")

HI_income_obesity <- get_income_obesity("Hawaii")
```

```{r Idaho, echo=FALSE}
ID_female_obesity <- get_female_obesity("Idaho")

ID_male_obesity <- get_male_obesity("Idaho")

ID_female_overweight <- get_female_overweight("Idaho")

ID_male_overweight <- get_male_overweight("Idaho")

ID_race_obesity <- get_race_obesity("Idaho")

ID_income_obesity <- get_income_obesity("Idaho")
```

```{r New York, echo=FALSE}
NY_female_obesity <- get_female_obesity("New York")

NY_male_obesity <- get_male_obesity("New York")

NY_female_overweight <- get_female_overweight("New York")

NY_male_overweight <- get_male_overweight("New York")

NY_race_obesity <- get_race_obesity("New York")

NY_income_obesity <- get_income_obesity("New York")
```

```{r Texas, echo=FALSE}
TX_female_obesity <- get_female_obesity("Texas")

TX_male_obesity <- get_male_obesity("Texas")

TX_female_overweight <- get_female_overweight("Texas")

TX_male_overweight <- get_male_overweight("Texas")

TX_race_obesity <- get_race_obesity("Texas")

TX_income_obesity <- get_income_obesity("Texas")
```

```{r graph, echo=FALSE}
tristate_female <- full_join(NY_female_obesity, TX_female_obesity, by = c("year_end", "gender", "location_desc","obesity")) %>%
  full_join(CA_female_obesity, by = c("year_end", "gender", "location_desc", "obesity")) %>%
  full_join(FL_female_obesity, by = c("year_end", "gender", "location_desc", "obesity"))

tristate_male <- full_join(NY_male_obesity, TX_male_obesity, by = c("year_end", "location_desc", "gender", "obesity")) %>%
  full_join(CA_male_obesity, by = c("year_end", "location_desc", "gender", "obesity")) %>%
  full_join(FL_male_obesity, by = c("year_end", "location_desc", "gender", "obesity"))


tristate_combined <- rbind(tristate_female, tristate_male)

tristate_combined %>%
  ggplot(aes(year_end, obesity, color = location_desc)) + geom_line() +
  facet_wrap(~gender) +
  labs(title = "Evolution of obesity rates in population by gender",
       subtitle = "Four most populated states",
       color = "State") +
       ylab("Percentage") +
       xlab("Year") +
  theme_classic()
```